{{
  exports.host = 'https://httpbin.org';
  exports.user = 'doe';
  exports.password = '12345678';
  exports.authorization = `Basic ${Buffer.from( exports.user + ":" + exports.password).toString('base64')}`
}}

###
# @name basicauth

GET {{host}}/basic-auth/{{user}}/{{password}}
Authorization:{{authorization}}

{{
  const assert = require('assert');
  assert.equal(basicauth.authenticated, true, "Basic Auth works");
}}