{{
  exports.authorization = `Basic ${Buffer.from( elastic_user + ":" + elastic_password).toString('base64')}`
}}

###
# @name elastic

GET {{elastic_uri}}/
Authorization:{{authorization}}

{{
  const assert = require('assert');
  assert.equal(elastic.version.number, "7.6.2", "elastic version is valid");
}}