{{#
  const {httpYacApi} = require('httpYac');
  const vscode = require('vscode');
  httpYacApi.httpRegionParsers.splice(1, 0, {
    parse: (lineReader,...args) => {
      const next = lineReader.next();
      if(next.value.textLine.startsWith('@')){
        vscode.window.showInformationMessage(next.value.textLine.substring(1));
        return {
          endLine: next.value.line
        };
      }
      return false;
    }
  });
}}

@It is me, Mario

https://www.google.de