

# @name keycloak
# @jwt
POST {{keycloak_url}}/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{keycloak_clientId}} {{keycloak_clientSecret}}

grant_type=client_credentials


###
# @name health
# @ref keycloak
GET {{spring_host}}/actuator/health
Authorization: Bearer {{keycloak.access_token}}

