name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        language: [ 'javascript' ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
        config-file: ./.github/codeql-config.yml
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm install
    - run: npm run lint
    - run: npm run package
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
