name: publish
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm run lint
    - name: Publish
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_TOKEN }}